"""Postgres-based job queue operations using SELECT ... FOR UPDATE SKIP LOCKED.

Split into submodules; this package re-exports the full former ``db.queue``
module surface so consumers import from ``db.queue`` unchanged.
"""

from __future__ import annotations

from db.storage import artifact_key, source_file_key

from ._chains import _job_chain_name, _mainnet_coalesced_chain
from .artifacts import (
    _artifact_row_to_value,
    count_analysis_children,
    get_all_artifacts,
    get_artifact,
    get_source_files,
    store_artifact,
    store_source_files,
)
from .discovery import (
    bulk_upsert_discovered_contracts,
    get_or_create_protocol,
    upsert_discovered_contract,
)
from .heartbeats import (
    DEFAULT_DAEMON_LEASE_TTL_S,
    DEFAULT_JOB_LEASE_TTL_S,
    DEFAULT_JOB_STALE_TIMEOUT,
    HEARTBEAT_AUDIT_SCOPE,
    HEARTBEAT_AUDIT_TEXT,
    HEARTBEAT_COVERAGE_VERIFY,
    HEARTBEAT_ENROLLMENT_RECONCILER,
    HEARTBEAT_EVENT_INDEXER,
    HEARTBEAT_OPS_ALERTER,
    HEARTBEAT_PROTOCOL_POLLER,
    HEARTBEAT_PROTOCOL_RESTAKING,
    HEARTBEAT_PROTOCOL_SCANNER,
    HEARTBEAT_PROTOCOL_SCORE,
    HEARTBEAT_PROTOCOL_TVL,
    HEARTBEAT_ROLE_HOLDER_PLANE,
    LeaseLost,
    _heartbeat_last_warned,
    record_heartbeat,
    renew_daemon_lease,
    try_acquire_daemon_lease,
)
from .jobs import (
    _check_lease_or_raise,
    advance_job,
    claim_job,
    complete_job,
    create_job,
    fail_job,
    fail_job_terminal,
    heartbeat_job,
    reclaim_stuck_jobs,
    reconcile_impl_job_for_proxy,
    release_job_lease,
    requeue_job,
    update_job_detail,
)
from .static_cache import (
    _MUTABLE_CONTRACT_FIELDS,
    _SEED_ARTIFACT_NAMES,
    _STATIC_ARTIFACT_NAMES,
    copy_row,
    copy_static_cache,
    copy_static_cache_cross_chain,
    find_completed_static_cache,
    find_existing_job_for_address,
    find_previous_company_inventory,
    is_known_proxy,
    proven_static_facts_schema_version,
)

__all__ = [
    "DEFAULT_DAEMON_LEASE_TTL_S",
    "DEFAULT_JOB_LEASE_TTL_S",
    "DEFAULT_JOB_STALE_TIMEOUT",
    "HEARTBEAT_AUDIT_SCOPE",
    "HEARTBEAT_AUDIT_TEXT",
    "HEARTBEAT_COVERAGE_VERIFY",
    "HEARTBEAT_ENROLLMENT_RECONCILER",
    "HEARTBEAT_EVENT_INDEXER",
    "HEARTBEAT_OPS_ALERTER",
    "HEARTBEAT_PROTOCOL_POLLER",
    "HEARTBEAT_PROTOCOL_RESTAKING",
    "HEARTBEAT_PROTOCOL_SCANNER",
    "HEARTBEAT_PROTOCOL_SCORE",
    "HEARTBEAT_PROTOCOL_TVL",
    "HEARTBEAT_ROLE_HOLDER_PLANE",
    "LeaseLost",
    "_MUTABLE_CONTRACT_FIELDS",
    "_SEED_ARTIFACT_NAMES",
    "_STATIC_ARTIFACT_NAMES",
    "_artifact_row_to_value",
    "_check_lease_or_raise",
    "_heartbeat_last_warned",
    "_job_chain_name",
    "_mainnet_coalesced_chain",
    "advance_job",
    "artifact_key",
    "bulk_upsert_discovered_contracts",
    "claim_job",
    "complete_job",
    "copy_row",
    "copy_static_cache",
    "copy_static_cache_cross_chain",
    "count_analysis_children",
    "create_job",
    "fail_job",
    "fail_job_terminal",
    "find_completed_static_cache",
    "find_existing_job_for_address",
    "find_previous_company_inventory",
    "get_all_artifacts",
    "get_artifact",
    "get_or_create_protocol",
    "get_source_files",
    "heartbeat_job",
    "is_known_proxy",
    "proven_static_facts_schema_version",
    "reclaim_stuck_jobs",
    "reconcile_impl_job_for_proxy",
    "record_heartbeat",
    "release_job_lease",
    "renew_daemon_lease",
    "requeue_job",
    "source_file_key",
    "store_artifact",
    "store_source_files",
    "try_acquire_daemon_lease",
    "update_job_detail",
    "upsert_discovered_contract",
]
