"""chain-qualify address_labels (invariant 12, audit finding F5)

Revision ID: c2d5e8f1a4b7
Revises: b4e1d8a52f39
Create Date: 2026-07-17 15:00:00.000000

The bare-address PK on ``address_labels`` collided for contracts deployed at the
same address on two chains. Move to the global-plus-override model (invariant
12): a surrogate ``id`` PK, a nullable chain-NAME ``chain`` column, and two
PARTIAL unique indexes.

Expand-contract (invariant 9), safe on POPULATED prod:
  * ``id`` is added as ``GENERATED BY DEFAULT AS IDENTITY`` — Postgres fills the
    sequence value into every existing row as part of the ADD COLUMN, so the new
    PK is populated without a separate backfill pass.
  * ``chain`` is added NULLABLE and stays that way BY DESIGN. ``chain IS NULL``
    is the "global label" state, which is precisely the semantics every legacy
    row already has (they were address-only). So there is NO data backfill and
    every existing row remains a global label with byte-identical behaviour.
  * The two partial unique indexes reproduce the old single-row-per-address
    guarantee: ``UNIQUE(address) WHERE chain IS NULL`` for globals (the only
    rows that exist pre-migration) plus ``UNIQUE(address, chain) WHERE chain IS
    NOT NULL`` for the new per-chain overrides. A plain ``UNIQUE(address,
    chain)`` was rejected because Postgres NULL≠NULL would let duplicate global
    rows in.

Adding a nullable column and an identity column are metadata-only in Postgres
11+/16 (no table rewrite), safe inside the default ``lock_timeout``. The table
is tiny (admin-curated labels), so the CREATE INDEX cost is negligible.

Downgrade stance (decided, not accidental): the pre-migration schema — a bare
``address`` PK — cannot represent two rows at one address, so downgrade is only
safe when NO chain-qualified rows exist. It therefore refuses (raises) if any
``chain IS NOT NULL`` row is present rather than silently dropping override
data; with only global rows it restores the original address PK cleanly.
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

revision: str = "c2d5e8f1a4b7"
down_revision: Union[str, Sequence[str], None] = "b4e1d8a52f39"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_PK = "address_labels_pkey"
_UQ_CHAIN = "uq_address_labels_address_chain"
_UQ_GLOBAL = "uq_address_labels_address_global"


def upgrade() -> None:
    # Drop the bare-address PK, then introduce the surrogate id. The identity
    # sequence auto-fills existing rows during ADD COLUMN, so id is non-null and
    # unique without a backfill.
    op.drop_constraint(_PK, "address_labels", type_="primary")
    op.add_column(
        "address_labels",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
    )
    op.create_primary_key(_PK, "address_labels", ["id"])

    # Nullable chain-NAME string. NULL = global label (every legacy row).
    op.add_column("address_labels", sa.Column("chain", sa.String(length=64), nullable=True))

    # Two partial unique indexes: one row per (address, chain) override, one
    # global row per address. NULL≠NULL forces the partial predicate rather than
    # a plain composite unique.
    op.create_index(
        _UQ_CHAIN,
        "address_labels",
        ["address", "chain"],
        unique=True,
        postgresql_where=sa.text("chain IS NOT NULL"),
    )
    op.create_index(
        _UQ_GLOBAL,
        "address_labels",
        ["address"],
        unique=True,
        postgresql_where=sa.text("chain IS NULL"),
    )


def downgrade() -> None:
    bind = op.get_bind()
    override_rows = bind.execute(sa.text("SELECT COUNT(*) FROM address_labels WHERE chain IS NOT NULL")).scalar()
    if override_rows:
        raise RuntimeError(
            f"cannot downgrade address_labels: {override_rows} chain-qualified row(s) exist and "
            "the restored bare-address primary key cannot represent per-chain overrides; delete "
            "them first if a downgrade is truly intended"
        )
    op.drop_index(_UQ_GLOBAL, table_name="address_labels")
    op.drop_index(_UQ_CHAIN, table_name="address_labels")
    op.drop_column("address_labels", "chain")
    op.drop_constraint(_PK, "address_labels", type_="primary")
    op.drop_column("address_labels", "id")
    op.create_primary_key(_PK, "address_labels", ["address"])
