"""Prepared response IO; no ORM graphs or unbounded in-process cache.

Unchanged source revisions permit reuse regardless of build age. Every origin
read validates the revisions; the edge gets at most 60s from that validation.
"""

from __future__ import annotations

import gzip
import hashlib
import io
import json
import logging
import os
from typing import Any

from fastapi import Request, Response
from fastapi.encoders import jsonable_encoder
from sqlalchemy import String, and_, case, cast, exists, func, literal, select
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Session

from db.jsonb import jsonb_state
from db.models import CompanyPageRevision, CompanyPageSnapshot, Protocol
from utils.compression import accepts_gzip

logger = logging.getLogger(__name__)
MAX_AGE_SECONDS = 60
MAX_JSON_BYTES = 32 * 1024 * 1024
MAX_GZIP_BYTES = 4 * 1024 * 1024


def cache_tag(name: str) -> str:
    """One bounded ASCII tag for every cached URL/encoding of a company."""
    return "psat-company-" + hashlib.sha256(name.encode()).hexdigest()


def enabled() -> bool:
    return os.getenv("PSAT_PREPARED_COMPANY_PAGES", "0") == "1"


def version() -> str:
    # A rolling deploy cannot serve a document generated by incompatible code.
    return "2:" + os.getenv("GIT_SHA", "local")


def encode(payload: Any) -> bytes:
    raw = json.dumps(jsonable_encoder(payload), ensure_ascii=False, allow_nan=False, separators=(",", ":")).encode()
    if len(raw) > MAX_JSON_BYTES:
        raise ValueError("Company page exceeds prepared JSON size limit")
    body = gzip.compress(raw, compresslevel=6, mtime=0)
    if len(body) > MAX_GZIP_BYTES:
        raise ValueError("Company page exceeds prepared gzip size limit")
    return body


def source_revisions(session: Session) -> dict[str, str | None]:
    """Capture the tokens in the SAME repeatable-read snapshot as both builds."""
    keys = sorted(session.info["company_page_dependencies"])
    versions = {
        key: token
        for key, token in session.execute(
            select(CompanyPageRevision.key, CompanyPageRevision.token).where(CompanyPageRevision.key.in_(keys))
        )
    }
    return {key: str(versions[key]) if key in versions else None for key in keys}


def revisions_current():
    """SQL predicate: a dirty response must never receive another cache TTL."""
    page = CompanyPageSnapshot
    revisions = case(
        (jsonb_state(page.source_revisions) == "object", page.source_revisions), else_=literal({}, type_=JSONB)
    )
    entries = func.jsonb_each_text(revisions).table_valued("key", "value")
    changed = (
        select(literal(1))
        .select_from(entries)
        .outerjoin(CompanyPageRevision, CompanyPageRevision.key == entries.c.key)
        .where(entries.c.value.is_distinct_from(cast(CompanyPageRevision.token, String)))
        .correlate(page)
    )
    return and_(
        revisions.has_key("all"),
        revisions.has_key(literal("protocol:") + cast(page.protocol_id, String)),
        ~exists(changed),
    )


def read_response(session: Session, request: Request, name: str, *, functions: bool = False) -> Response | None:
    if (
        not enabled()
        or request.query_params
        or any(
            d.strip().lower() in {"no-cache", "no-store", "max-age=0"}
            for d in request.headers.get("cache-control", "").split(",")
        )
    ):
        return None
    blob = CompanyPageSnapshot.functions_gzip if functions else CompanyPageSnapshot.overview_gzip
    row = session.execute(
        select(blob, CompanyPageSnapshot.source_started_at, func.statement_timestamp())
        .join(Protocol, Protocol.id == CompanyPageSnapshot.protocol_id)
        .where(
            Protocol.name == name,
            CompanyPageSnapshot.company_name == name,
            CompanyPageSnapshot.version == version(),
            revisions_current(),
            CompanyPageSnapshot.source_started_at <= func.clock_timestamp(),
            blob.is_not(None),
        )
    ).first()
    if row is None:
        return None
    body, source_at, now = row
    if len(body) > MAX_GZIP_BYTES:
        return None
    headers = {
        "Cache-Tag": cache_tag(name),
        "Vary": "Accept-Encoding",
        "X-PSAT-Prepared-At": source_at.isoformat(),
        "X-PSAT-Validated-At": now.isoformat(),
        "X-PSAT-Response-Source": "prepared",
        # Internal header consumed and stripped by the origin boundary.
        "X-PSAT-Fresh-Until": str(now.timestamp() + MAX_AGE_SECONDS),
    }
    if accepts_gzip(request.headers.get("accept-encoding", "")):
        headers["Content-Encoding"] = "gzip"
    else:
        try:
            with gzip.GzipFile(fileobj=io.BytesIO(body)) as compressed:
                body = compressed.read(MAX_JSON_BYTES + 1)
            if len(body) > MAX_JSON_BYTES:
                return None
        except (OSError, EOFError):
            logger.warning("Invalid prepared company gzip", extra={"company": name})
            return None
    return Response(body, media_type="application/json", headers=headers)
