"""Prepared response IO; no ORM graphs or unbounded in-process cache.

Freshness is measured from the start of the source snapshot, not publication.
The edge must spend only the remaining freshness budget, never reset it.
"""

from __future__ import annotations

import gzip
import io
import json
import logging
import math
import os
import uuid
from datetime import timedelta
from typing import Any

from fastapi import Request, Response
from fastapi.encoders import jsonable_encoder
from sqlalchemy import func, select
from sqlalchemy.dialects.postgresql import insert as pg_insert
from sqlalchemy.orm import Session

from db.models import CompanyPageSnapshot, Protocol
from utils.compression import accepts_gzip
from utils.edge import has_credentials

logger = logging.getLogger(__name__)
MAX_AGE_SECONDS = 60
MAX_JSON_BYTES = 32 * 1024 * 1024
MAX_GZIP_BYTES = 4 * 1024 * 1024


def enabled() -> bool:
    return os.getenv("PSAT_PREPARED_COMPANY_PAGES", "0") == "1"


def version() -> str:
    # A rolling deploy cannot serve a document generated by incompatible code.
    return "1:" + os.getenv("GIT_SHA", "local")


def encode(payload: Any) -> bytes:
    raw = json.dumps(jsonable_encoder(payload), ensure_ascii=False, allow_nan=False, separators=(",", ":")).encode()
    if len(raw) > MAX_JSON_BYTES:
        raise ValueError("Company page exceeds prepared JSON size limit")
    body = gzip.compress(raw, compresslevel=6, mtime=0)
    if len(body) > MAX_GZIP_BYTES:
        raise ValueError("Company page exceeds prepared gzip size limit")
    return body


def mark_dirty(session: Session, protocol_id: int) -> None:
    """A hint in the producer's transaction; periodic refresh is the backstop."""
    if not enabled():
        return
    try:
        with session.begin_nested():
            session.execute(
                pg_insert(CompanyPageSnapshot)
                .values(protocol_id=protocol_id, dirty_token=uuid.uuid4())
                .on_conflict_do_update(index_elements=["protocol_id"], set_={"dirty_token": uuid.uuid4()})
            )
    except Exception:
        logger.warning("Company page dirty mark failed", exc_info=True, extra={"protocol_id": protocol_id})


def read_response(session: Session, request: Request, name: str, *, functions: bool = False) -> Response | None:
    if (
        not enabled()
        or request.query_params
        or has_credentials(request)
        or request.scope.get("state", {}).get("edge_operator", False)
        or any(
            d.strip().lower() in {"no-cache", "no-store", "max-age=0"}
            for d in request.headers.get("cache-control", "").split(",")
        )
    ):
        return None
    blob = CompanyPageSnapshot.functions_gzip if functions else CompanyPageSnapshot.overview_gzip
    row = session.execute(
        select(blob, CompanyPageSnapshot.source_started_at, func.clock_timestamp())
        .join(Protocol, Protocol.id == CompanyPageSnapshot.protocol_id)
        .where(
            Protocol.name == name,
            CompanyPageSnapshot.company_name == name,
            CompanyPageSnapshot.version == version(),
            CompanyPageSnapshot.source_started_at > func.clock_timestamp() - timedelta(seconds=MAX_AGE_SECONDS - 1),
            blob.is_not(None),
        )
    ).first()
    if row is None:
        return None
    body, source_at, now = row
    remaining = math.floor(MAX_AGE_SECONDS - (now - source_at).total_seconds())
    if not 0 < remaining <= MAX_AGE_SECONDS or len(body) > MAX_GZIP_BYTES:
        return None
    headers = {
        "Vary": "Accept-Encoding",
        "X-PSAT-Prepared-At": source_at.isoformat(),
        "X-PSAT-Response-Source": "prepared",
        # Internal header consumed and stripped by the origin boundary.
        "X-PSAT-Fresh-Until": str(source_at.timestamp() + MAX_AGE_SECONDS),
    }
    if accepts_gzip(request.headers.get("accept-encoding", "")):
        headers["Content-Encoding"] = "gzip"
    else:
        try:
            with gzip.GzipFile(fileobj=io.BytesIO(body)) as compressed:
                body = compressed.read(MAX_JSON_BYTES + 1)
            if len(body) > MAX_JSON_BYTES:
                return None
        except (OSError, EOFError):
            logger.warning("Invalid prepared company gzip", extra={"company": name})
            return None
    return Response(body, media_type="application/json", headers=headers)
