"""Build the semantic ``effects`` artifact for a contract.

Walks Slither IR for every externally-callable function on a contract
and emits a typed record describing the function's *effects*: state
writes, external calls, delegatecalls, contract creations, and
selfdestructs — including those reached transitively through internal
calls. The artifact is the semantic sink/effect carrier for downstream
consumers (``cross_contract.py``, ``tracking.py``,
``effective_permissions.py``).

Why a separate artifact (vs. extending ``predicate_trees``):
``predicate_trees`` deliberately omits *unguarded* functions
(``predicate_artifacts.py:44``) — the resolver treats absence as
"public / unguarded". For sink/effect discovery we want a record per
externally-callable function regardless of guard structure, so a
publicly callable sensitive action (e.g. unprotected ``mint``) is
still surfaced to the policy stage.

Function inclusion:
  * external/public functions: included.
  * constructor: skipped (matches ``predicate_artifacts._is_externally_callable``;
    constructor effects are tracked elsewhere).
  * fallback / receive: INCLUDED. They have real effect semantics —
    receive can hold ETH; fallback often delegatecalls. The
    predicate-tree builder skips them because their "guard" semantics
    are unusual, but that's not a reason to drop them from sink
    discovery.
  * internal / private: never appear directly; their effects are
    surfaced through their external callers via transitive walk.

Plane-0 facts (this artifact is the machine-checkable substrate a later
claims plane reads):
  * every sink carries an ``origin`` — ``body`` for the function's own
    logic, ``guard`` for anything reached only through a modifier. A
    modifier's auth call (``auth.canCall``) is a guard fact, not an
    effect, so it never drives a label.
  * ``state_writes`` records each write at ``var`` / ``member`` /
    ``assembly_slot`` granularity with a ``hygiene_class`` marking the
    non-role writes (constants, ``*StorageLocation`` slot pseudo-vars,
    reentrancy guards, view-function ghost writes).
  * ``value_flows`` records asset movement with a ``from == address(this)``
    direction correction and native ``transfer``/``send`` sinks.
"""

from __future__ import annotations

from .build import (
    _effect_info_for_function,
    _effect_targets_from_sinks,
    _reconcile_value_flow_labels,
    _record_prefers,
    _writer_selectors_for,
    build_effects,
)
from .origins import (
    _CALL_IR_OPS,
    _CALL_WALK_DEFS,
    _CALLER_SUPPLIED_TAGS,
    _ELEMENT_ROOT_TAGS,
    _ELEMENT_WALK_DEFS,
    _ENGINE_BUNDLE,
    _MAX_RECORD_KEY_LEVELS,
    _MAX_RECORD_MEMBER_DEPTH,
    _MERGE_RESOLVE_DEPTH,
    _MIN_GT_OPS,
    _MIN_LT_OPS,
    _NO_TARGET_VAR,
    _RECORD_KEY_ORIGINS,
    _RETURN_ORIGIN_ACTIVE,
    _RETURN_ORIGIN_DEPTH,
    _SAME_CONTEXT_CALL_OPS,
    _TOKEN_OWNER_SELECTOR,
    _WRITER_SURFACE_CLOSED,
    ElementRecordSite,
    _amount_is_provably_zero,
    _amount_kind_from_sources,
    _arg_origin,
    _base_name,
    _bindings_for_call,
    _branch_return_value,
    _build_unit_ctx,
    _call_amount_origin,
    _call_irs,
    _call_origin,
    _call_param_argument_indexes,
    _call_standard_origin,
    _callee_is_two_arg_min,
    _callee_return_origin,
    _capped_min_call,
    _capped_ternary,
    _classify_site,
    _element_kind,
    _element_origin,
    _element_record_site,
    _element_root_origins,
    _element_walk,
    _ElementRoot,
    _engine_bundle_for,
    _EngineBundle,
    _fn_def_by_id,
    _fold_sites,
    _forwarded_param_sources,
    _ir_source_operands,
    _is_caller_supplied_leaf,
    _is_capped_by_balance,
    _is_derivation,
    _is_self_balance_read,
    _is_subtraction,
    _is_zero_literal,
    _key_conversion_is_lossy,
    _member_name,
    _merged_caller_supplied,
    _one_call_origin,
    _operand_is_direct,
    _operand_param_index,
    _origin_to_amount_kind,
    _origin_to_target_kind,
    _param_derived_index,
    _param_indexes_of,
    _phi_of,
    _reaches_merged_local,
    _reads_element,
    _resolve_copies,
    _return_values,
    _single_param_origin,
    _single_phi_input,
    _site_breakdown,
    _source_neutral_origin,
    _source_param_index,
    _state_var_target_kind,
    _target_kind_from_sources,
    _target_state_var_name,
    _target_variable_site,
    _type_bit_width,
    _UnitCtx,
)
from .selectors import (
    _DISPATCH_SEARCH_DEPTH,
    _ERC20_TRANSFER_FROM_SELECTOR,
    _ERC20_TRANSFER_SELECTOR,
    _EVM_CALL_OPCODES,
    _FIXED_BYTES_TYPE,
    _TOKEN_FIRST_BODY_DEPTH,
    _auto_getter_selector,
    _callee_signature,
    _dispatches_a_call,
    _erc20_selector_evidence,
    _erc20_selectors_issued,
    _function_full_name,
    _ir_operands,
    _is_evm_call_opcode,
    _is_fallback_or_receive,
    _node_irs,
    _own_selector,
    _selector_for,
    _selector_of_constant,
    _selector_of_member_access,
    _token_first_transfer,
)
from .setters import (
    _ALIASED_WRITES,
    _SETTER_SCAN_COMPLETE,
    _SETTER_VARS,
    _STORAGE_ALIAS_DEPTH,
    _UNSCANNED_SAMPLE,
    _aliased_storage_writes,
    _arg_is_param,
    _resolve_storage_origin,
    _setter_scan_complete,
    _setter_state_vars,
    _storage_param_write_status,
)
from .sinks import (
    _bare_callee_name,
    _build_sink_records,
    _classify_node_irs,
    _fold_receivers,
    _is_externally_observable,
    _is_modifier_call,
    _is_state_changing_entry_point,
    _is_view_or_pure,
    _node_kind_state_writes,
    _receiver_descriptor,
    _receiver_not_determined,
    _sink_id,
    _walk_unit_for_sinks,
)
from .state_writes import (
    _GUARD_WALK_DEPTH,
    _REENTRANCY_GUARD_NAMES,
    _REENTRANCY_GUARDS,
    _SLOT_POINTER_CONSTANTS,
    _collect_reentrancy_guard_vars,
    _collect_slot_pointer_constants,
    _hygiene_class_for_var,
    _is_reentrancy_guard_var,
    _nodes_around_placeholder,
    _nodes_state_writes,
    _state_write_facts,
    _struct_member_types,
    _transitive_member_writes,
    _units_of,
)
from .types import (
    _AMBIGUOUS_PULL_SELECTOR,
    _ERC20_PULL_SELECTORS,
    _ERC20_SEND_SELECTORS,
    _ERC721_IDENTITY_SELECTORS,
    _SPECIFIC_EFFECT_LABELS,
    _TOKEN_IDENTITY_AMOUNT,
    SCHEMA_VERSION,
    EffectInfo,
    EffectsArtifact,
    KindTier,
    ReceiverDescriptor,
    SinkRecord,
    StateWriteFact,
    TokenSlotEntry,
    TokenSlots,
    ValueFlow,
)
from .value_flow import (
    _VALUE_WALK_DEPTH_CAP,
    _arg_is_address_this,
    _attach_amount_record,
    _attach_target_variable,
    _fold_param_index,
    _value_flow_facts,
)

__all__ = [
    "_ALIASED_WRITES",
    "_AMBIGUOUS_PULL_SELECTOR",
    "_CALLER_SUPPLIED_TAGS",
    "_CALL_IR_OPS",
    "_CALL_WALK_DEFS",
    "_DISPATCH_SEARCH_DEPTH",
    "_ELEMENT_ROOT_TAGS",
    "_ELEMENT_WALK_DEFS",
    "_ENGINE_BUNDLE",
    "_ERC20_PULL_SELECTORS",
    "_ERC20_SEND_SELECTORS",
    "_ERC20_TRANSFER_FROM_SELECTOR",
    "_ERC20_TRANSFER_SELECTOR",
    "_ERC721_IDENTITY_SELECTORS",
    "_EVM_CALL_OPCODES",
    "EffectInfo",
    "EffectsArtifact",
    "ElementRecordSite",
    "_ElementRoot",
    "_EngineBundle",
    "_FIXED_BYTES_TYPE",
    "_GUARD_WALK_DEPTH",
    "KindTier",
    "_MAX_RECORD_KEY_LEVELS",
    "_MAX_RECORD_MEMBER_DEPTH",
    "_MERGE_RESOLVE_DEPTH",
    "_MIN_GT_OPS",
    "_MIN_LT_OPS",
    "_NO_TARGET_VAR",
    "_RECORD_KEY_ORIGINS",
    "_REENTRANCY_GUARDS",
    "_REENTRANCY_GUARD_NAMES",
    "_RETURN_ORIGIN_ACTIVE",
    "_RETURN_ORIGIN_DEPTH",
    "ReceiverDescriptor",
    "_SAME_CONTEXT_CALL_OPS",
    "SCHEMA_VERSION",
    "_SETTER_SCAN_COMPLETE",
    "_SETTER_VARS",
    "_SLOT_POINTER_CONSTANTS",
    "_SPECIFIC_EFFECT_LABELS",
    "_STORAGE_ALIAS_DEPTH",
    "SinkRecord",
    "StateWriteFact",
    "_TOKEN_FIRST_BODY_DEPTH",
    "_TOKEN_IDENTITY_AMOUNT",
    "_TOKEN_OWNER_SELECTOR",
    "TokenSlotEntry",
    "TokenSlots",
    "_UNSCANNED_SAMPLE",
    "_UnitCtx",
    "_VALUE_WALK_DEPTH_CAP",
    "ValueFlow",
    "_WRITER_SURFACE_CLOSED",
    "_aliased_storage_writes",
    "_amount_is_provably_zero",
    "_amount_kind_from_sources",
    "_arg_is_address_this",
    "_arg_is_param",
    "_arg_origin",
    "_attach_amount_record",
    "_attach_target_variable",
    "_auto_getter_selector",
    "_bare_callee_name",
    "_base_name",
    "_bindings_for_call",
    "_branch_return_value",
    "build_effects",
    "_build_sink_records",
    "_build_unit_ctx",
    "_call_amount_origin",
    "_call_irs",
    "_call_origin",
    "_call_param_argument_indexes",
    "_call_standard_origin",
    "_callee_is_two_arg_min",
    "_callee_return_origin",
    "_callee_signature",
    "_capped_min_call",
    "_capped_ternary",
    "_classify_node_irs",
    "_classify_site",
    "_collect_reentrancy_guard_vars",
    "_collect_slot_pointer_constants",
    "_dispatches_a_call",
    "_effect_info_for_function",
    "_effect_targets_from_sinks",
    "_element_kind",
    "_element_origin",
    "_element_record_site",
    "_element_root_origins",
    "_element_walk",
    "_engine_bundle_for",
    "_erc20_selector_evidence",
    "_erc20_selectors_issued",
    "_fn_def_by_id",
    "_fold_param_index",
    "_fold_receivers",
    "_fold_sites",
    "_forwarded_param_sources",
    "_function_full_name",
    "_hygiene_class_for_var",
    "_ir_operands",
    "_ir_source_operands",
    "_is_caller_supplied_leaf",
    "_is_capped_by_balance",
    "_is_derivation",
    "_is_evm_call_opcode",
    "_is_externally_observable",
    "_is_fallback_or_receive",
    "_is_modifier_call",
    "_is_reentrancy_guard_var",
    "_is_self_balance_read",
    "_is_state_changing_entry_point",
    "_is_subtraction",
    "_is_view_or_pure",
    "_is_zero_literal",
    "_key_conversion_is_lossy",
    "_member_name",
    "_merged_caller_supplied",
    "_node_irs",
    "_node_kind_state_writes",
    "_nodes_around_placeholder",
    "_nodes_state_writes",
    "_one_call_origin",
    "_operand_is_direct",
    "_operand_param_index",
    "_origin_to_amount_kind",
    "_origin_to_target_kind",
    "_own_selector",
    "_param_derived_index",
    "_param_indexes_of",
    "_phi_of",
    "_reaches_merged_local",
    "_reads_element",
    "_receiver_descriptor",
    "_receiver_not_determined",
    "_reconcile_value_flow_labels",
    "_record_prefers",
    "_resolve_copies",
    "_resolve_storage_origin",
    "_return_values",
    "_selector_for",
    "_selector_of_constant",
    "_selector_of_member_access",
    "_setter_scan_complete",
    "_setter_state_vars",
    "_single_param_origin",
    "_single_phi_input",
    "_sink_id",
    "_site_breakdown",
    "_source_neutral_origin",
    "_source_param_index",
    "_state_var_target_kind",
    "_state_write_facts",
    "_storage_param_write_status",
    "_struct_member_types",
    "_target_kind_from_sources",
    "_target_state_var_name",
    "_target_variable_site",
    "_token_first_transfer",
    "_transitive_member_writes",
    "_type_bit_width",
    "_units_of",
    "_value_flow_facts",
    "_walk_unit_for_sinks",
    "_writer_selectors_for",
]
