"""Layer 1: one job's planes to per-function signal rows. Pure and read-only.

Resolves nothing across contracts (principals stay ``function_principals`` references, value stays entity keys), since
max-per-entity, principal units and subsumption need the whole protocol.

Undetermined witnesses reach signals only via :func:`not_determined_signal_defaults` or :meth:`Tri.not_determined`.
Severity is either built up from proven components (``pause.set``) or a class constant refined downward; it is never
escalated by a missing constraint witness, so an unread delegatecall destination yields ``severity = not_determined``.
"""

from __future__ import annotations

from utils.scoring_status import (
    SELF_SERVICE_DISCLOSE_SIBLING,
    SELF_SERVICE_DISCLOSE_UPGRADE,
)

from .claims import (
    _TIER_RANK,
    _TIER_TOKENS,
    _amount_kinds,
    _best_tier,
    _claim_ids,
    _claims,
    _considered_out_flows,
    _static_destination_shape,
    _target_kinds,
    _tier,
)
from .destination import (
    _DESTINATION_MEET_RANK,
    _UNDETERMINED_DESTINATION,
    _caller_relative_destination,
    _Destination,
    _exec_destination,
    _flow_destination,
    _fork_caller_arbitrary_param,
    _meet_destinations,
)
from .facts import (
    _ORPHAN_SAMPLE,
    _SOLMATE_MUTATOR_SELECTORS,
    _TIMELOCK_ENTRYPOINTS,
    _TRANSCRIPT_CACHE,
    _W2_ARM_RANK,
    ASSET_IDENTITY_ARTIFACT_ABSENT,
    ASSET_IDENTITY_ARTIFACT_MALFORMED,
    ASSET_IDENTITY_JOB_ABSENT,
    ASSET_IDENTITY_LOADED,
    ASSET_IDENTITY_NO_RECEIVERS,
    COMMON_GATES,
    DESTINATION_GATES,
    FLOW_GATES,
    PAUSE_SET_GATES,
    REPOINT_ADMISSIBLE_TIERS,
    W2_INVARIANT_NOT_DETERMINED,
    W2_NO_STATE_VAR_RECEIVER,
    W2_PLANE_ABSENT,
    W2_SELECTOR_UNRESOLVED,
    W2_STATUS_NOT_RESOLVED,
    _asset_identity,
    _ContractFacts,
    _f,
    _function_is_self_gated,
    _is_true,
    _licensed_reach_entities,
    _load_contract_facts,
    _lower,
    _pause_unset_principals,
    _proven_number,
    _registry_owner,
    _TranscriptReader,
    clear_transcript_cache,
    distill_contract_signals,
    distill_job_signals,
)
from .flow_reach import (
    _cited_verdict_entry,
    _flow_reach,
    _no_reach,
    _proving_execution_gate,
    _Reach,
    _repointed_entities,
    _verdict_bearing_entries,
)
from .msg_value import (
    _AMOUNT_TIER_DISPOSITIVE,
    _MSG_VALUE_NOT_ASKED,
    _MSG_VALUE_REFUSAL_PREFIX,
    _MSG_VALUE_TARGET_ARMS,
    MSG_VALUE_ARM_PASSTHROUGH,
    MSG_VALUE_ARM_SELF_RETURN,
    MSG_VALUE_REPETITION_RESIDUAL,
    _mentions_msg_value,
    _msg_value_return,
    _MsgValueReturn,
)
from .self_service import (
    _PROVENANCE_CALLER_GATE,
    _SELF_SERVICE_NOT_ASKED,
    _SELF_SERVICE_PROVEN_STATE,
    _SS_PAYEE_NOT_CALLER_RELATIVE,
    _SS_REFUSAL_PREFIX,
    _SS_SOURCE_NOT_SELF,
    _SS_UNREAD_FLOW,
    SELF_SERVICE_BASIS,
    SELF_SERVICE_UNCHARGED_NOTE,
    _flow_asset_class,
    _self_service_bound,
    _SelfServiceBound,
)
from .signals import (
    _build_signal,
    _cite_refused_repoints,
    _exact_empty_gate,
    _flow_gates,
    _latch_gate,
    _openness,
    _pause_gates,
    _pause_severity,
    _reach_for_claim,
    _reach_rank,
    _severity,
    _signals_for_function,
    _token_identity,
)

__all__ = [
    "SELF_SERVICE_DISCLOSE_SIBLING",
    "SELF_SERVICE_DISCLOSE_UPGRADE",
    "ASSET_IDENTITY_ARTIFACT_ABSENT",
    "ASSET_IDENTITY_ARTIFACT_MALFORMED",
    "ASSET_IDENTITY_JOB_ABSENT",
    "ASSET_IDENTITY_LOADED",
    "ASSET_IDENTITY_NO_RECEIVERS",
    "COMMON_GATES",
    "DESTINATION_GATES",
    "FLOW_GATES",
    "MSG_VALUE_ARM_PASSTHROUGH",
    "MSG_VALUE_ARM_SELF_RETURN",
    "MSG_VALUE_REPETITION_RESIDUAL",
    "PAUSE_SET_GATES",
    "REPOINT_ADMISSIBLE_TIERS",
    "SELF_SERVICE_BASIS",
    "SELF_SERVICE_UNCHARGED_NOTE",
    "W2_INVARIANT_NOT_DETERMINED",
    "W2_NO_STATE_VAR_RECEIVER",
    "W2_PLANE_ABSENT",
    "W2_SELECTOR_UNRESOLVED",
    "W2_STATUS_NOT_RESOLVED",
    "_AMOUNT_TIER_DISPOSITIVE",
    "_ContractFacts",
    "_DESTINATION_MEET_RANK",
    "_Destination",
    "_MSG_VALUE_NOT_ASKED",
    "_MSG_VALUE_REFUSAL_PREFIX",
    "_MSG_VALUE_TARGET_ARMS",
    "_MsgValueReturn",
    "_ORPHAN_SAMPLE",
    "_PROVENANCE_CALLER_GATE",
    "_Reach",
    "_SELF_SERVICE_NOT_ASKED",
    "_SELF_SERVICE_PROVEN_STATE",
    "_SOLMATE_MUTATOR_SELECTORS",
    "_SS_PAYEE_NOT_CALLER_RELATIVE",
    "_SS_REFUSAL_PREFIX",
    "_SS_SOURCE_NOT_SELF",
    "_SS_UNREAD_FLOW",
    "_SelfServiceBound",
    "_TIER_RANK",
    "_TIER_TOKENS",
    "_TIMELOCK_ENTRYPOINTS",
    "_TRANSCRIPT_CACHE",
    "_TranscriptReader",
    "_UNDETERMINED_DESTINATION",
    "_W2_ARM_RANK",
    "_amount_kinds",
    "_asset_identity",
    "_best_tier",
    "_build_signal",
    "_caller_relative_destination",
    "_cite_refused_repoints",
    "_cited_verdict_entry",
    "_claim_ids",
    "_claims",
    "_considered_out_flows",
    "_exact_empty_gate",
    "_exec_destination",
    "_f",
    "_flow_asset_class",
    "_flow_destination",
    "_flow_gates",
    "_flow_reach",
    "_fork_caller_arbitrary_param",
    "_function_is_self_gated",
    "_is_true",
    "_latch_gate",
    "_licensed_reach_entities",
    "_load_contract_facts",
    "_lower",
    "_meet_destinations",
    "_mentions_msg_value",
    "_msg_value_return",
    "_no_reach",
    "_openness",
    "_pause_gates",
    "_pause_severity",
    "_pause_unset_principals",
    "_proven_number",
    "_proving_execution_gate",
    "_reach_for_claim",
    "_reach_rank",
    "_registry_owner",
    "_repointed_entities",
    "_self_service_bound",
    "_severity",
    "_signals_for_function",
    "_static_destination_shape",
    "_target_kinds",
    "_tier",
    "_token_identity",
    "_verdict_bearing_entries",
    "clear_transcript_cache",
    "distill_contract_signals",
    "distill_job_signals",
]
