"""Layer 2 — the whole-protocol grade fold. Pure, read-only, deterministic.

The fold is a recompute, never an accumulator. Three facts make a running total
wrong: value is MAX per (entity, asset) so two contracts reaching one vault must
charge it once; principal units are cross-contract and get RE-KEYED when a later
contract reveals an owner overlap; and which finding subsumes which is only
decidable with the whole finding set present.

Its population is the signal plane and nothing else — read through the one
pinned, totally ordered query — plus the resolution planes in
:mod:`services.scoring.planes`, which is where a reference becomes a unit, a
dollar or a breadth floor.

THE ROOT RULE
-------------
**Never substitute an available field for an unread one.** Every ``x or y`` on a
nullable or three-state expression is that substitution written as an idiom: an
owner set that did not resolve is not the threshold, an unread delay is not zero,
an unpriced entity is not ``$0.00``, and a principal address is not its own owner
set unless the principal IS a key. Where a witness is missing the answer is the
uncredited rung, an explicit ``None``, or a withheld row — chosen so the mistake
costs a credit rather than fabricating one. Every remaining fallback in this
module is guarded by a proof that the substituted value IS the fact.

Every arithmetic branch fails closed. A signal whose severity was not proven is
not scored; a value that could not be priced falls to the unpriced branch rather
than to zero; a malformed gate envelope withholds its own row rather than
raising out of the whole fold.
"""

from __future__ import annotations

from services.scoring import constants as K
from services.scoring import planes as P
from services.scoring.fold.ceilings import (
    _CEILING_KIND_BOUNDS,
    _CEILING_KIND_CLAUSES,
    _MISSING_LINK_CHAIN,
    _MISSING_LINK_OF,
    _PUBLISHED_CENT,
    _UNPRICED_ASSET_STATES,
    _asset_coverage,
    _asset_set_completeness,
    _bound_direction,
    _ceiling_bearing_basis,
    _ceiling_bound_phrase,
    _ceiling_source_phrase,
    _ceiling_untightened,
    _ceilings_present,
    _coverage_bearing_basis,
    _disclose_order_ties,
    _disposed_ceiling_clause,
    _disposition_carrier,
    _disposition_scope,
    _named_zeros,
    _order_tie_reading,
    _partially_priced_entities,
    _reconcile_sheet_ceilings,
    _sheet_ceiling_records,
    _sheet_ceiling_totals,
    _sheet_ceiling_totals_reading,
    _unresolved_levers,
    _unresolved_stake,
)
from services.scoring.fold.closure import (
    _CENSUS_GATE_CAPABILITIES,
    _CONFERRAL_RANK,
    _REFUSAL_RANK,
    _SCOPE_KIND_RANK,
    ACT_AS_CALLER_UNREACHED,
    _behind_the_frontier,
    _closure,
    _hop_census,
)
from services.scoring.fold.composition import (
    _ARM_ONLY_CAUSES,
    _GATE_ONLY_ROUTE_CAUSES,
    _WITHHELD_CAUSE_ORDER,
    _admit_composed,
    _compose,
    _composed_order,
    _ComposedMagnitude,
    _composition_report,
    _counted,
    _destination_magnitudes,
    _first_differing_component,
    _pool_composed,
    _select_composed,
    _withheld_cause,
    _withheld_cause_clause,
    _withheld_cause_key,
)
from services.scoring.fold.confidence import (
    _CREDIT_PATH_CLAUSES,
    CREDIT_PATH_COMPOSED,
    CREDIT_PATH_OWN,
    CREDIT_PATH_SHEET_CEILING,
    _confidence,
    _credit_path_reading,
    _entities_outside_perimeter,
    _mixed_witness_cause,
)
from services.scoring.fold.contributions import (
    _ceiling_kind,
    _entity_contribution,
    _instance_contributions,
    _sheet_ceiling,
    _state_word,
    _unbounded_figure,
    _unbounded_reading,
    _witnessed_magnitude,
)
from services.scoring.fold.core import (
    _CITATION_EVIDENCE_KEYS,
    CITATION_CAP,
    _aggregate,
    _attach,
    _cited,
    _composition_totals,
    _execution_carriers,
    _execution_fault_census,
    _execution_fault_warning,
    _fold_severity,
    _instance,
    _keyset_independence,
    _kn,
    _member_weakness,
    _recovery_refs,
    _row_value,
    _safe_weakness,
    _UnitResolver,
    compute_protocol_score,
)
from services.scoring.fold.disclosures import (
    _NOTE_WARNINGS,
    _UNCHARGED_CONDITIONAL_TOKENS,
    _UNCHARGED_RESIDUAL_TOKENS,
    _collect_disclosures,
    _counterfactual,
    _is_uncharged_product,
    _population_disposition,
    _summarise_warnings,
    _uncharged_product,
    _warning,
)
from services.scoring.fold.gates import (
    ANYONE,
    GATE_PAYLOAD_SHAPES,
    GATE_PROVEN_TOKENS,
    NUMERIC_GATES,
    REQUIRED_GATES,
    REQUIRED_GATES_BY_CLAIM,
    SINGLE_ASSET_CLASSES,
    _gate,
    _is_number,
    _is_principal_ref,
    _malformed_gates,
    _payload_has_shape,
    _row_for,
    _signal_execution,
    _signal_identity,
)
from services.scoring.fold.grade import (
    _exposure_coverage,
    _gap_reading,
    _grade,
)
from services.scoring.fold.readings import (
    _BAND_PREFIX,
    _BOUNDED_BY_SHEET,
    _BOUNDED_BY_WITNESS,
    _CEILING_CLOSING,
    _CEILING_COVERAGE_SHORTFALL_PREFIX,
    _CEILING_SOURCE_READINGS,
    _COMPOSED_SOURCE_READINGS,
    _DISPOSED_SHEET_DOES_NOT_BOUND,
    _ORDER_COMPONENT_NAMES,
    _PUBLISHED_DECIMALS,
    _SHEET_CEILING_DIRECTION_BASIS,
    _SHEET_CEILING_INCOMPLETE_CAUSES,
    _TRIMMED_TO_AN_UNPROVEN_CEILING,
    _WITHHELD_ARM_READINGS,
    _WITHHELD_CLOSING,
    _WITHHELD_OPENING,
    _WITNESS_STATE_CLAIM,
    _WITNESS_STATE_UNRANKED,
    ARM_GATE_ONLY,
    ARM_NOT_DETERMINED,
    ARM_REPUBLISHED_DIRECT,
    ARM_WITHHELD,
    BOUND_DIRECTION_CEILING,
    BOUND_DIRECTION_FLOOR,
    BOUND_DIRECTION_NOT_DETERMINED,
    CEILING_KIND_COMPOSED,
    CEILING_KIND_SHEET,
    CEILING_REFUSAL_REASONS,
    COMPOSITION_ARMS,
    SHEET_BOUND_REFUSED_BY_DISPOSITION,
    SHEET_CEILING_BOUND_DIRECTIONS,
    SHEET_CEILING_REFUSED_PREFIX,
    _coverage_shortfall,
    _round_published,
    _sheet_ceiling_direction_basis,
)
from services.scoring.fold.types import (
    _AdmissionPlanes,
    _DestinationMagnitude,
    _gate_claim,
    _Instance,
    _Row,
    _RowValue,
    _WalkedHop,
    _WithheldComposition,
)
from services.scoring.population import current_signals_with_faults
from services.scoring.reach import (
    HOP_REFUSED_CONDITION,
    HOP_REFUSED_CONFERRAL,
    HOP_REFUSED_SCOPE,
)
from services.scoring.reach import (
    hop_bound as _hop_bound,
)
from services.scoring.schema import (
    NOT_DETERMINED,
    FunctionSignal,
    ScoreDocument,
    Tri,
    entity_key,
)
from utils import execution_record as EX
from utils.execution_record import PROVING_EXECUTION_KEY
from utils.scoring_status import (
    GRADE_FAULT_DEGRADED,
    GRADE_STATE_COMPUTED,
    GRADE_STATE_NOT_DETERMINED,
    MAGNITUDE_STATE_PROVEN_CEILING,
    MAGNITUDE_STATE_PROVEN_EXACT,
    MAGNITUDE_STATE_PROVEN_FLOOR,
    MAGNITUDE_STATE_PROVEN_UPPER_BOUND,
    MAGNITUDE_STATES_UPPER_BOUNDING,
    MODEL_VERSION,
    OPENNESS_NOT_DETERMINED,
    OPENNESS_OPEN,
    PRINCIPAL_STATE_ENUMERATED,
    PRINCIPAL_STATE_NONE_REQUIRED,
    PRINCIPAL_STATE_NOT_DETERMINED,
    SCORE_TRIGGER_MANUAL,
    SEVERITY_STATE_PROVEN,
    VALUE_STATE_PROVEN_NO_REACH,
    VALUE_STATE_PROVEN_REACH,
)

__all__ = [
    "ACT_AS_CALLER_UNREACHED",
    "ANYONE",
    "ARM_GATE_ONLY",
    "ARM_NOT_DETERMINED",
    "ARM_REPUBLISHED_DIRECT",
    "ARM_WITHHELD",
    "BOUND_DIRECTION_CEILING",
    "BOUND_DIRECTION_FLOOR",
    "BOUND_DIRECTION_NOT_DETERMINED",
    "CEILING_KIND_COMPOSED",
    "CEILING_KIND_SHEET",
    "CEILING_REFUSAL_REASONS",
    "CITATION_CAP",
    "COMPOSITION_ARMS",
    "CREDIT_PATH_COMPOSED",
    "CREDIT_PATH_OWN",
    "CREDIT_PATH_SHEET_CEILING",
    "EX",
    "FunctionSignal",
    "GATE_PAYLOAD_SHAPES",
    "GATE_PROVEN_TOKENS",
    "GRADE_FAULT_DEGRADED",
    "GRADE_STATE_COMPUTED",
    "GRADE_STATE_NOT_DETERMINED",
    "HOP_REFUSED_CONDITION",
    "HOP_REFUSED_CONFERRAL",
    "HOP_REFUSED_SCOPE",
    "K",
    "MAGNITUDE_STATES_UPPER_BOUNDING",
    "MAGNITUDE_STATE_PROVEN_CEILING",
    "MAGNITUDE_STATE_PROVEN_EXACT",
    "MAGNITUDE_STATE_PROVEN_FLOOR",
    "MAGNITUDE_STATE_PROVEN_UPPER_BOUND",
    "MODEL_VERSION",
    "NOT_DETERMINED",
    "NUMERIC_GATES",
    "OPENNESS_NOT_DETERMINED",
    "OPENNESS_OPEN",
    "P",
    "PRINCIPAL_STATE_ENUMERATED",
    "PRINCIPAL_STATE_NONE_REQUIRED",
    "PRINCIPAL_STATE_NOT_DETERMINED",
    "PROVING_EXECUTION_KEY",
    "REQUIRED_GATES",
    "REQUIRED_GATES_BY_CLAIM",
    "SCORE_TRIGGER_MANUAL",
    "SEVERITY_STATE_PROVEN",
    "SHEET_BOUND_REFUSED_BY_DISPOSITION",
    "SHEET_CEILING_BOUND_DIRECTIONS",
    "SHEET_CEILING_REFUSED_PREFIX",
    "SINGLE_ASSET_CLASSES",
    "ScoreDocument",
    "Tri",
    "VALUE_STATE_PROVEN_NO_REACH",
    "VALUE_STATE_PROVEN_REACH",
    "_ARM_ONLY_CAUSES",
    "_AdmissionPlanes",
    "_BAND_PREFIX",
    "_BOUNDED_BY_SHEET",
    "_BOUNDED_BY_WITNESS",
    "_CEILING_CLOSING",
    "_CEILING_COVERAGE_SHORTFALL_PREFIX",
    "_CEILING_KIND_BOUNDS",
    "_CEILING_KIND_CLAUSES",
    "_CEILING_SOURCE_READINGS",
    "_CENSUS_GATE_CAPABILITIES",
    "_CITATION_EVIDENCE_KEYS",
    "_COMPOSED_SOURCE_READINGS",
    "_CONFERRAL_RANK",
    "_CREDIT_PATH_CLAUSES",
    "_ComposedMagnitude",
    "_DISPOSED_SHEET_DOES_NOT_BOUND",
    "_DestinationMagnitude",
    "_GATE_ONLY_ROUTE_CAUSES",
    "_Instance",
    "_MISSING_LINK_CHAIN",
    "_MISSING_LINK_OF",
    "_NOTE_WARNINGS",
    "_ORDER_COMPONENT_NAMES",
    "_PUBLISHED_CENT",
    "_PUBLISHED_DECIMALS",
    "_REFUSAL_RANK",
    "_Row",
    "_RowValue",
    "_SCOPE_KIND_RANK",
    "_SHEET_CEILING_DIRECTION_BASIS",
    "_SHEET_CEILING_INCOMPLETE_CAUSES",
    "_TRIMMED_TO_AN_UNPROVEN_CEILING",
    "_UNCHARGED_CONDITIONAL_TOKENS",
    "_UNCHARGED_RESIDUAL_TOKENS",
    "_UNPRICED_ASSET_STATES",
    "_UnitResolver",
    "_WITHHELD_ARM_READINGS",
    "_WITHHELD_CAUSE_ORDER",
    "_WITHHELD_CLOSING",
    "_WITHHELD_OPENING",
    "_WITNESS_STATE_CLAIM",
    "_WITNESS_STATE_UNRANKED",
    "_WalkedHop",
    "_WithheldComposition",
    "_admit_composed",
    "_aggregate",
    "_asset_coverage",
    "_asset_set_completeness",
    "_attach",
    "_behind_the_frontier",
    "_bound_direction",
    "_ceiling_bearing_basis",
    "_ceiling_bound_phrase",
    "_ceiling_kind",
    "_ceiling_source_phrase",
    "_ceiling_untightened",
    "_ceilings_present",
    "_cited",
    "_closure",
    "_collect_disclosures",
    "_compose",
    "_composed_order",
    "_composition_report",
    "_composition_totals",
    "_confidence",
    "_counted",
    "_counterfactual",
    "_coverage_bearing_basis",
    "_coverage_shortfall",
    "_credit_path_reading",
    "_destination_magnitudes",
    "_disclose_order_ties",
    "_disposed_ceiling_clause",
    "_disposition_carrier",
    "_disposition_scope",
    "_entities_outside_perimeter",
    "_entity_contribution",
    "_execution_carriers",
    "_execution_fault_census",
    "_execution_fault_warning",
    "_exposure_coverage",
    "_first_differing_component",
    "_fold_severity",
    "_gap_reading",
    "_gate",
    "_gate_claim",
    "_grade",
    "_hop_bound",
    "_hop_census",
    "_instance",
    "_instance_contributions",
    "_is_number",
    "_is_principal_ref",
    "_is_uncharged_product",
    "_keyset_independence",
    "_kn",
    "_malformed_gates",
    "_member_weakness",
    "_mixed_witness_cause",
    "_named_zeros",
    "_order_tie_reading",
    "_partially_priced_entities",
    "_payload_has_shape",
    "_pool_composed",
    "_population_disposition",
    "_reconcile_sheet_ceilings",
    "_recovery_refs",
    "_round_published",
    "_row_for",
    "_row_value",
    "_safe_weakness",
    "_select_composed",
    "_sheet_ceiling",
    "_sheet_ceiling_direction_basis",
    "_sheet_ceiling_records",
    "_sheet_ceiling_totals",
    "_sheet_ceiling_totals_reading",
    "_signal_execution",
    "_signal_identity",
    "_state_word",
    "_summarise_warnings",
    "_unbounded_figure",
    "_unbounded_reading",
    "_uncharged_product",
    "_unresolved_levers",
    "_unresolved_stake",
    "_warning",
    "_withheld_cause",
    "_withheld_cause_clause",
    "_withheld_cause_key",
    "_witnessed_magnitude",
    "compute_protocol_score",
    "current_signals_with_faults",
    "entity_key",
]
