"""Predicate builder — produces a ``PredicateTree`` per function.

For each function:
  1. Run ``RevertDetector`` to find all gated revert paths.
  2. Run ``ProvenanceEngine`` to classify every SSA value's source(s).
  3. For each RevertGate, walk the condition value's defining IR back
     to its structural shape (Binary equality, Index membership, Unary
     negation, HighLevelCall returning bool, ecrecover comparison) and
     emit a ``LeafPredicate`` with kind + operator + operands.
  4. Apply polarity normalization: ``if (R) revert`` becomes the leaf
     for the allowed condition (NOT R), with the NOT pushed into the
     leaf's operator (no NOT survives in the tree).
  5. Combine leaves into a tree: multiple sequential gates AND at the
     root.

This module is the main user of ``ProvenanceEngine`` + ``RevertDetector``
and the producer of the semantic ``predicate_tree`` artifact field.

Scope of this initial cut: equality / membership leaves with the
caller_authority detection rules from v6 round-5 #1. external_bool /
signature_auth / comparison / unsupported leaves are added in
follow-ups (this commit lays the scaffold + the two most common kinds).
"""

from __future__ import annotations

from ..provenance import (
    EMPTY,
    TOP,
    ProvenanceEngine,
    ProvenanceMap,
    is_top,
)
from ._helpers import (
    _apply_polarity,
    _binary_op,
    _expand_key_operand,
    _find_defining_ir,
    _find_index_base,
    _gate_references_caller,
    _is_hash_or_encode_call,
    _make_leaf,
    _reconstruct_index_chain,
    _scan_node_for_lvalue,
    _unsupported_leaf,
    _value_type_of_index_ir,
)
from .authority import (
    _ADDRESS_TYPED_SOURCES,
    _CALLER_SOURCES,
    _classify_authority_equality,
    _classify_authority_membership,
    _operand_is_address_typed,
)
from .confidence import (
    _derive_confidence,
    apply_confidence_to_tree,
)
from .control_flow import (
    _ALWAYS_REVERTS_MAX_DEPTH,
    _branch_value_is_only_true,
    _build_if_else_returns_or_children,
    _callee_always_reverts,
    _detect_assembly_combinator_op,
    _find_callee_return_value,
    _forward_reachable_node_ids,
    _guards_contain_opening,
    _if_condition_value,
    _is_literal_false,
    _node_has_unclassified_call,
    _node_is_type,
    _node_terminates_control,
    _resolve_internal_call_return,
    _return_guard_gate,
    _return_literal,
)
from .leaves import (
    _ADDITIVE_BINARY_TYPES,
    _COMPARISON_SWAP,
    _YUL_EXTERNAL_CALL_PREFIXES,
    EIP_1271_MAGIC_VALUE,
    _attach_int_constant_value,
    _build_binary_leaf,
    _build_external_bool_leaf,
    _build_generic_external_set_descriptor,
    _build_index_membership_leaf,
    _build_self_gate_leaf,
    _build_solidity_call_leaf,
    _build_truthy_leaf,
    _build_unary_leaf,
    _callee_signature,
    _callee_state_mutability,
    _coerce_constant_value,
    _find_external_call_const_pair,
    _find_index_value_pair,
    _is_eip1271_magic,
    _is_mask_operand,
    _library_reaches_external_call,
    _literal_to_hex,
    _operand_sort_key,
    _selector_for_signature,
    _self_gate_or_truthy_leaf,
    _stamp_absorbed_operands,
    _stamp_param_keyed_authority_mapping,
    _swap_operator,
    _try_external_auth_oracle,
    _try_membership_via_value_compare,
    _try_threshold_membership,
)
from .operands import (
    _ELEMENT_CHAIN_CAP,
    _MAX_ELEMENT_MEMBER_DEPTH,
    _attach_element_read,
    _attach_state_constant_value,
    _attach_value_type,
    _bytes32_constant_expression_value,
    _classify_solidity_variable,
    _coerce_bytes32_hex,
    _defining_reference_ir,
    _derived_from_sort_key,
    _derived_view_call_source,
    _element_access_chain,
    _element_key_param_index,
    _element_read_fields,
    _key_definition_is_merged,
    _operand_for_value,
    _picked_source_operand,
    _published_source_key,
    _single_string_literal,
    _source_sort_key,
    _source_to_operand,
    _sources_for_value,
    _sources_from_destination,
    _ssa_definitions,
    _state_variable_bytes32_constant_value,
    _value_type_name,
)
from .tree import (
    _INLINED_GATE_KINDS,
    _attach_call_site_arg_origins,
    _attach_call_site_arg_origins_to_tree,
    _build_chain_bindings,
    _build_internal_call_leaf,
    _build_internal_call_or_and_subtree,
    _build_leaf_from_gate,
    _build_subtree_from_gate,
    _build_subtree_from_value,
    _cache_key_for,
    _call_site_arg_origins,
    _classify_leaf_from_ir,
    _function_returns_bool,
    _gate_condition_is_caller_eq_neq,
    _helper_engine_cache,
    _inline_gate_callee_stack,
    _inline_helper_revert_gates_enabled,
    _internal_call_revert_gate_subtrees,
    _operand_value_provenance,
    _tag_tree_leaves_basis,
    _tree_has_caller_tainted_leaf,
    build_predicate_tree,
    build_return_predicate_tree,
)

__all__ = [
    "EIP_1271_MAGIC_VALUE",
    "EMPTY",
    "ProvenanceEngine",
    "ProvenanceMap",
    "TOP",
    "_ADDITIVE_BINARY_TYPES",
    "_ADDRESS_TYPED_SOURCES",
    "_ALWAYS_REVERTS_MAX_DEPTH",
    "_CALLER_SOURCES",
    "_COMPARISON_SWAP",
    "_ELEMENT_CHAIN_CAP",
    "_INLINED_GATE_KINDS",
    "_MAX_ELEMENT_MEMBER_DEPTH",
    "_YUL_EXTERNAL_CALL_PREFIXES",
    "_apply_polarity",
    "_attach_call_site_arg_origins",
    "_attach_call_site_arg_origins_to_tree",
    "_attach_element_read",
    "_attach_int_constant_value",
    "_attach_state_constant_value",
    "_attach_value_type",
    "_binary_op",
    "_branch_value_is_only_true",
    "_build_binary_leaf",
    "_build_chain_bindings",
    "_build_external_bool_leaf",
    "_build_generic_external_set_descriptor",
    "_build_if_else_returns_or_children",
    "_build_index_membership_leaf",
    "_build_internal_call_leaf",
    "_build_internal_call_or_and_subtree",
    "_build_leaf_from_gate",
    "_build_self_gate_leaf",
    "_build_solidity_call_leaf",
    "_build_subtree_from_gate",
    "_build_subtree_from_value",
    "_build_truthy_leaf",
    "_build_unary_leaf",
    "_bytes32_constant_expression_value",
    "_cache_key_for",
    "_call_site_arg_origins",
    "_callee_always_reverts",
    "_callee_signature",
    "_callee_state_mutability",
    "_classify_authority_equality",
    "_classify_authority_membership",
    "_classify_leaf_from_ir",
    "_classify_solidity_variable",
    "_coerce_bytes32_hex",
    "_coerce_constant_value",
    "_defining_reference_ir",
    "_derive_confidence",
    "_derived_from_sort_key",
    "_derived_view_call_source",
    "_detect_assembly_combinator_op",
    "_element_access_chain",
    "_element_key_param_index",
    "_element_read_fields",
    "_expand_key_operand",
    "_find_callee_return_value",
    "_find_defining_ir",
    "_find_external_call_const_pair",
    "_find_index_base",
    "_find_index_value_pair",
    "_forward_reachable_node_ids",
    "_function_returns_bool",
    "_gate_condition_is_caller_eq_neq",
    "_gate_references_caller",
    "_guards_contain_opening",
    "_helper_engine_cache",
    "_if_condition_value",
    "_inline_gate_callee_stack",
    "_inline_helper_revert_gates_enabled",
    "_internal_call_revert_gate_subtrees",
    "_is_eip1271_magic",
    "_is_hash_or_encode_call",
    "_is_literal_false",
    "_is_mask_operand",
    "_key_definition_is_merged",
    "_library_reaches_external_call",
    "_literal_to_hex",
    "_make_leaf",
    "_node_has_unclassified_call",
    "_node_is_type",
    "_node_terminates_control",
    "_operand_for_value",
    "_operand_is_address_typed",
    "_operand_sort_key",
    "_operand_value_provenance",
    "_picked_source_operand",
    "_published_source_key",
    "_reconstruct_index_chain",
    "_resolve_internal_call_return",
    "_return_guard_gate",
    "_return_literal",
    "_scan_node_for_lvalue",
    "_selector_for_signature",
    "_self_gate_or_truthy_leaf",
    "_single_string_literal",
    "_source_sort_key",
    "_source_to_operand",
    "_sources_for_value",
    "_sources_from_destination",
    "_ssa_definitions",
    "_stamp_absorbed_operands",
    "_stamp_param_keyed_authority_mapping",
    "_state_variable_bytes32_constant_value",
    "_swap_operator",
    "_tag_tree_leaves_basis",
    "_tree_has_caller_tainted_leaf",
    "_try_external_auth_oracle",
    "_try_membership_via_value_compare",
    "_try_threshold_membership",
    "_unsupported_leaf",
    "_value_type_name",
    "_value_type_of_index_ir",
    "apply_confidence_to_tree",
    "build_predicate_tree",
    "build_return_predicate_tree",
    "is_top",
]
